version: '3.5'
services:
  apache:
    build:
      context: './build/${APACHE_BUILD_FOLDER:-apache}'
      dockerfile: Dockerfile
    restart: always
    networks:
      static:
        ipv4_address: '${IP_ADDR_APACHE:?please define IP_ADDR_APACHE variable}'
    volumes:
      - '${PROJECT_SRC:?please define PROJECT_SRC variable}:/var/www/html'
  mysql:
    build:
      context: './build/${MYSQL_BUILD_FOLDER:-mysql}'
      dockerfile: Dockerfile
    restart: always
    networks:
      static:
        ipv4_address: '${IP_ADDR_MYSQL:?please define IP_ADDR_MYSQL variable}'
    volumes:
      - 'mysql:/var/lib/mysql'
    environment:
      - 'MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}'
      - 'MYSQL_DATABASE=${MYSQL_DATABASE}'
      - 'MYSQL_USER=${MYSQL_USER}'
      - 'MYSQL_PASSWORD=${MYSQL_PASSWORD}'
volumes:
  mysql:
networks:
  static:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: '${IP_ADDR_SUBNET:?please define IP_ADDR_SUBNET}'
